var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('MiContainer',{attrs:{"narrow":"","gap":"2"}},[_c('nu-flow',{attrs:{"gap":"1"}},[_c('nu-heading',{attrs:{"level":"1","size":"h1|||h3"}},[_vm._v("\n      "+_vm._s(_vm.$t('personal_settings.header'))+"\n    ")]),_c('nu-line')],1),_c('nu-flow',{attrs:{"gap":"2"}},[_c('nu-flow',{attrs:{"gap":"1"}},[_c('StickyHeader',[_c('nu-heading',{attrs:{"level":"2"}},[_vm._v(_vm._s(_vm.$t('settings.interface.header')))])],1),_c('nu-grid',{attrs:{"items":"center start","columns":"auto 1fr","gap":".5"}},[_c('nu-block',[_vm._v(_vm._s(_vm.$t('settings.interface.theme'))+":")]),_c('nu-btn-group',{attrs:{"value":_vm.settings.theme},on:{"input":function($event){return _vm.changeTheme($event.detail)}}},[_c('nu-btn',{attrs:{"value":"light"}},[_vm._v(_vm._s(_vm.$t('label.light')))]),_c('nu-btn',{attrs:{"value":"dark"}},[_vm._v(_vm._s(_vm.$t('label.dark')))]),_c('nu-btn',{attrs:{"value":"auto"}},[_vm._v(_vm._s(_vm.$t('label.auto')))])],1),_c('nu-block',[_vm._v(_vm._s(_vm.$t('settings.interface.reduced_motion'))+":")]),_c('nu-btn-group',{attrs:{"value":_vm.settings.reducedMotion},on:{"input":function($event){return _vm.changeReducedMotion($event.detail)}}},[_c('nu-btn',{attrs:{"value":"off"}},[_vm._v(_vm._s(_vm.$t('label.off')))]),_c('nu-btn',{attrs:{"value":"on"}},[_vm._v(_vm._s(_vm.$t('label.on')))]),_c('nu-btn',{attrs:{"value":"auto"}},[_vm._v(_vm._s(_vm.$t('label.auto')))])],1),_c('nu-block',[_vm._v(_vm._s(_vm.$t('settings.interface.high_contrast'))+":")]),_c('nu-btn-group',{attrs:{"value":_vm.settings.highContrast},on:{"input":function($event){return _vm.changeHighContrast($event.detail)}}},[_c('nu-btn',{attrs:{"value":"off"}},[_vm._v(_vm._s(_vm.$t('label.off')))]),_c('nu-btn',{attrs:{"value":"on"}},[_vm._v(_vm._s(_vm.$t('label.on')))])],1)],1)],1),_c('MiForm',{ref:"profileForm",attrs:{"schema":_vm.profileForm,"columns":"repeat(3, 1fr)","gap":"1"},on:{"validation":_vm.profileChanged},scopedSlots:_vm._u([{key:"default",fn:function(ref){
var $invalid = ref.$invalid;
var $changed = ref.$changed;
return [_c('StickyHeader',{attrs:{"column":"1 / span 3"}},[_c('nu-heading',{attrs:{"level":"2"}},[_vm._v(_vm._s(_vm.$t('personal_settings.data')))])],1),_c('nu-grid',[_c('MiFormLabel',{attrs:{"name":"firstName"}}),_c('MiFormInput',{attrs:{"name":"firstName","placeholder":false}})],1),_c('nu-grid',[_c('MiFormLabel',{attrs:{"name":"lastName"}}),_c('MiFormInput',{attrs:{"name":"lastName","placeholder":false}})],1)]}}]),model:{value:(_vm.profileData),callback:function ($$v) {_vm.profileData=$$v},expression:"profileData"}}),_c('MiForm',{ref:"accountForm",attrs:{"schema":_vm.accountForm,"columns":"repeat(3, 1fr)||1fr","gap":"1","padding":"1 0 0 0"},on:{"input":_vm.accountChanged},scopedSlots:_vm._u([{key:"default",fn:function(ref){
var $invalid = ref.$invalid;
var $changed = ref.$changed;
var $v = ref.$v;
return [_c('StickyHeader',{attrs:{"column":"1 / span 3||1fr"}},[_c('nu-heading',{attrs:{"level":"2"}},[_vm._v(_vm._s(_vm.$t('settings.profile.account_information')))])],1),_c('nu-grid',[_c('MiFormLabel',{attrs:{"name":"email"}}),_c('MiFormInput',{attrs:{"name":"email","placeholder":false}})],1),_c('nu-grid',[_c('MiFormLabel',{attrs:{"name":"newPassword"}}),_c('MiFormInput',{attrs:{"name":"newPassword","placeholder":false}})],1),_c('nu-grid',[_c('MiFormLabel',{attrs:{"name":"confirmPassword"}}),_c('MiFormInput',{attrs:{"name":"confirmPassword","placeholder":false}})],1),_c('nu-grid',{attrs:{"row":"3 / span 2||auto","column":"3 / span 1||auto"}},[_c('nu-card',{attrs:{"mod":"transparent","shadow":"","border":""}},[_c('MiContent',{directives:[{name:"markdown",rawName:"v-markdown",value:('settings.profile.password_requirements'),expression:"'settings.profile.password_requirements'"}]})],1)],1),_c('nu-block',{attrs:{"column":"1 / span 2||1","mod":"minor"}},[_c('p',[_vm._v(_vm._s(_vm.$t('settings.profile.email_notice')))])]),_c('nu-grid',[_c('MiFormLabel',{attrs:{"name":"currentPassword"}}),_c('MiFormInput',{attrs:{"name":"currentPassword","placeholder":false}})],1),_c('nu-grid',{attrs:{"flow":"column","column":"1 / span 2||1","content":"start","gap":".5"}},[_c('nu-btn',{attrs:{"special":"","disabled":!_vm.isEmailChangeAllowed($v)},on:{"tap":_vm.changeEmail}},[_vm._v("\n          "+_vm._s(_vm.$t('settings.profile.change_email'))+"\n        ")]),_c('nu-btn',{attrs:{"special":"","disabled":!_vm.isPasswordChangeAllowed($v)},on:{"tap":_vm.changePassword}},[_vm._v("\n          "+_vm._s(_vm.$t('settings.profile.change_password'))+"\n        ")])],1),_c('nu-grid',{attrs:{"column":"1 / span 2||1"}},[_c('MiContent',{staticStyle:{"font-size":"var(--size-very-small)"}},[_c('p',[(_vm.accountErrorCode)?_c('nu-badge',{attrs:{"theme":"danger"}},[_vm._v("\n              "+_vm._s(_vm.$t(("server_errors." + _vm.accountErrorCode)))+"\n            ")]):_vm._e()],1)])],1)]}}]),model:{value:(_vm.accountData),callback:function ($$v) {_vm.accountData=$$v},expression:"accountData"}})],1)],1)}
var staticRenderFns = []

export { render, staticRenderFns }