var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('MiContainer',[_c('ConnectWidget'),_c('ExpiredWidget'),_c('StickyHeader',{attrs:{"columns":"auto auto||auto","items":"center start"}},[_c('nu-heading',{attrs:{"size":"h1|||h3"}},[_vm._v("\n      "+_vm._s(_vm.$t('pnl.header_statement'))+"\n      "),_c('MiInfo',{directives:[{name:"tooltip",rawName:"v-tooltip.bottom",value:(_vm.$markdown(_vm.$t('pnl.tooltip'))),expression:"$markdown($t('pnl.tooltip'))",modifiers:{"bottom":true}}]})],1),_c('nu-grid',{attrs:{"flow":"column","gap":"2"}},[_c('nu-btn-group',{attrs:{"value":String(_vm.percentage)},on:{"input":function($event){_vm.percentage = $event.detail === 'true'}}},[_c('nu-btn',{attrs:{"padding":".5 .75","value":"false"}},[_c('nu-icon',{attrs:{"name":"dollar-sign"}})],1),_c('nu-btn',{attrs:{"padding":".5 .75","value":"true"}},[_c('nu-icon',{attrs:{"name":"percent"}})],1)],1),_c('nu-flex',{attrs:{"gap":".5","items":"center"}},[_c('nu-block',[_vm._v("\n          "+_vm._s(_vm.$t('label.year'))+":\n        ")]),_c('MiSelect',{attrs:{"width":"7","options":_vm.yearOptions,"value":_vm.year,"disabled":_vm.integrationStatus !== 'active'},on:{"input":_vm.changeYear}})],1)],1)],1),(_vm.data.grossRevenue)?_c('nu-grid-table',{attrs:{"columns":("17rem repeat(" + (_vm.columns.length) + ", 1fr)"),"gap":"var(--nu-pixel) 0","radius":"","shadow":"","border":"","mod":"minor"}},[_c('nu-block',{attrs:{"mod":"table-sticky-left"}}),_vm._l((_vm.columns),function(column,index){return _c('nu-grid',{key:("header:" + column),attrs:{"theme":"minor","role":"columnheader","padding":".5","mod":("xs w6 " + (index === 12 ? 'uppercase' : '')),"items":"center"}},[_vm._v("\n      "+_vm._s(column)+"\n    ")])}),_vm._l((_vm.schema),function(field){return [(field.border)?_c('nu-line',{key:((field.id) + ":border")}):_vm._e(),_c('nu-grid',{key:((field.id) + ":label"),class:{
          '-hovered': _vm.hovered === field.id,
          '-nu-w5': !field.bold,
          '-nu-w7': field.bold,
        },attrs:{"theme":"minor","mod":"table-sticky-left","padding":!_vm.isSectionEmpty(field.id) ? 0 : (".5 .5 .5 " + (field.bold ? '2.5' : '3'))},on:{"mouseenter":function($event){return _vm.onFieldHover(field.id)},"mouseleave":function($event){return _vm.onFieldBlur()}}},[(_vm.isSectionEmpty(field.id))?_c('nu-block',[_vm._v("\n          "+_vm._s(_vm.getLabel(field.id))+"\n        ")]):_c('nu-btn',{attrs:{"cell":"","columns":((field.bold ? 1.5 : '0 1.5') + " 1fr"),"gap":".5","padding":".5","items":"start","place":"stretch"},on:{"tap":function($event){return _vm.toggleRow(field.id)}}},[(!field.bold)?_c('nu-block'):_vm._e(),_c('MiDropdownIcon',{attrs:{"value":_vm.expanded.includes(field.id),"place":"center"}}),_vm._v("\n          "+_vm._s(_vm.getLabel(field.id))+"\n        ")],1)],1),_vm._l((_vm.columns),function(column,index){return _c('nu-block',{key:((field.id) + ":" + column),staticClass:"-nu-right -nu-xs -nu-monospace",class:{ '-hovered': _vm.hovered === field.id, '-nu-w6': field.bold },style:(("\n          --cell-line-height: " + (_vm.hovered === field.id && _vm.data[field.id]
            ? Math.abs(_vm.getPercent(field.id, index))
            : 0) + "%;\n        ")),attrs:{"padding":".75 .75 .25 .5"}},[(!field.abstract)?_c('span',{staticClass:"mi-cell-value"},[_vm._v("\n          "+_vm._s(_vm.getValue(field.id, index))+"\n        ")]):_vm._e(),_c('span',{staticClass:"mi-cell-line",class:{ '-negative': _vm.getPercent(field.id, index) < 0 }})])}),(field.items && _vm.expanded.includes(field.id))?[_vm._l((field.items),function(item){return [(field.empty !== false || !_vm.isRowEmpty(item))?[_c('nu-block',{key:(item + ":label"),attrs:{"theme":"minor","mod":"table-sticky-left sm","padding":".5 0 .5 3.5rem"},on:{"mouseenter":function($event){return _vm.onFieldHover(item)},"mouseleave":function($event){return _vm.onFieldBlur()}}},[_vm._v("\n              "+_vm._s(_vm.getLabel(item))+"\n            ")]),_vm._l((_vm.columns),function(column,index){return _c('nu-block',{key:(item + ":" + column),staticClass:"-nu-right -nu-xs -nu-monospace",class:{ '-hovered': _vm.hovered === item, '-nu-w6': field.bold },style:(("\n              --cell-line-height: " + (_vm.hovered === item && _vm.data[item]
                ? Math.abs(_vm.getPercent(item, index))
                : 0) + "%;\n            ")),attrs:{"padding":".75 .75 .25 .5"}},[_c('span',{staticClass:"mi-cell-value"},[_vm._v("\n              "+_vm._s(_vm.getValue(item, index))+"\n            ")]),_c('span',{staticClass:"mi-cell-line",class:{ '-negative': _vm.getPercent(item, index) < 0 }})])})]:_vm._e()]})]:_vm._e()]})],2):_vm._e()],1)}
var staticRenderFns = []

export { render, staticRenderFns }