var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('MiModal',{ref:"root",attrs:{"width":"31","height":"22"},scopedSlots:_vm._u([{key:"default",fn:function(ref){
var resolve = ref.resolve;
var reject = ref.reject;
return [_c('nu-grid',{attrs:{"rows":"auto auto 1fr auto auto"}},[_c('nu-grid',{attrs:{"padding":"1"}},[_c('nu-heading',{directives:[{name:"t",rawName:"v-t",value:('unit.add_tracked_product'),expression:"'unit.add_tracked_product'"}],attrs:{"level":"2"}})],1),_c('nu-tablist',{attrs:{"content":"start","padding":"0 1","value":_vm.addType},on:{"input":function($event){_vm.addType = $event.detail}}},[_c('nu-tab',{attrs:{"value":"asin","disabled":""}},[_vm._v("By ASIN")]),_c('nu-tab',{attrs:{"value":"manual"}},[_vm._v("Manually")])],1),_c('nu-line'),_c('MiForm',{directives:[{name:"show",rawName:"v-show",value:(_vm.addType === 'asin'),expression:"addType === 'asin'"}],ref:"form",attrs:{"schema":_vm.productAsinFormSchema},on:{"validation":_vm.onValidation},scopedSlots:_vm._u([{key:"default",fn:function(ref){
var $valid = ref.$valid;
var $formData = ref.$formData;
var $pending = ref.$pending;
return [_c('nu-grid',{attrs:{"padding":"1"}},[_c('MiFormLabel',{attrs:{"name":"asin"}}),_c('MiFormInput',{attrs:{"name":"asin","autofocus":""}}),_c('MiFormError',{attrs:{"name":"asin"}}),_c('nu-grid',{attrs:{"columns":"auto 1fr","items":"start","gap":"1"}},[(!_vm.productData)?_c('nu-grid',{attrs:{"height":"3"}},[_vm._v("\n            "+_vm._s($pending ? _vm.$t('label.loading') : ' ')+"\n          ")]):_vm._e(),(_vm.productData)?_c('nu-grid',[_c('MiPicture',{attrs:{"width":"3"}},[_c('img',{attrs:{"src":_vm.productData.attributes.smallImage.url,"alt":_vm.productData.name}})])],1):_vm._e(),(_vm.productData)?_c('nu-grid',[_vm._v("\n            "+_vm._s(_vm.productData.name)+"\n          ")]):_vm._e()],1)],1),_c('nu-line'),_c('nu-grid',{attrs:{"flow":"column","gap":".5","padding":".5 1","content":"start"}},[_c('nu-btn',{directives:[{name:"t",rawName:"v-t",value:('actions.add_product'),expression:"'actions.add_product'"}],attrs:{"special":"","disabled":!$valid},on:{"tap":function($event){return resolve($formData)}}}),_c('nu-btn',{directives:[{name:"t",rawName:"v-t",value:('actions.cancel'),expression:"'actions.cancel'"}],on:{"tap":reject}})],1)]}}],null,true)}),_c('MiForm',{directives:[{name:"show",rawName:"v-show",value:(_vm.addType === 'manual'),expression:"addType === 'manual'"}],attrs:{"schema":_vm.productAddingFormSchema},scopedSlots:_vm._u([{key:"default",fn:function(ref){
var $valid = ref.$valid;
var $formData = ref.$formData;
return [_c('nu-grid',{attrs:{"padding":"1","columns":"1fr 1fr 1fr","gap":"0 1"}},[_c('nu-grid',{attrs:{"column":"1 / -1","items":"stretch"}},[_c('MiFormLabel',{attrs:{"name":"name"}}),_c('MiFormInput',{attrs:{"name":"name","autofocus":""}})],1),_c('nu-grid',[_c('MiFormLabel',{attrs:{"name":"salesPrice"}}),_c('MiFormInput',{attrs:{"name":"salesPrice"}})],1),_c('nu-grid',[_c('MiFormLabel',{attrs:{"name":"fbaFee"}}),_c('MiFormInput',{attrs:{"name":"fbaFee"}})],1),_c('nu-grid',[_c('MiFormLabel',{attrs:{"name":"unitLandedCost"}}),_c('MiFormInput',{attrs:{"name":"unitLandedCost"}})],1)],1),_c('nu-line'),_c('nu-grid',{attrs:{"flow":"column","gap":".5","padding":".5 1","content":"start"}},[_c('nu-btn',{directives:[{name:"t",rawName:"v-t",value:('actions.add_product'),expression:"'actions.add_product'"}],attrs:{"special":"","disabled":!$valid},on:{"tap":function($event){return resolve($formData)}}}),_c('nu-btn',{directives:[{name:"t",rawName:"v-t",value:('actions.cancel'),expression:"'actions.cancel'"}],on:{"tap":reject}})],1)]}}],null,true)})],1)]}}])})}
var staticRenderFns = []

export { render, staticRenderFns }